import Head from "next/head";
import Link from "next/link";

const FirstPost = () => {
  return (
    <>
      <Head>
        <title>firstPost</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>最初の投稿</h1>
        <Link href="/">ホームへ戻る</Link>
      </div>
    </>
  );
};

export default FirstPost;
