import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const myPhoto = "/images/my_photo.JPG";

const FirstPost = () => {
  return (
    <div>
      <Head>
        <title>firstPost</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>最初の投稿</h1>
      <Image src={myPhoto} alt="myPhoto" width={100} height={100} />
      <div>
        <Link href="/">ホームへ戻る</Link>
      </div>
    </div>
  );
};

export default FirstPost;
